services:
  - type: web
    name: waha-service
    runtime: image
    plan: free
    image:
      url: devlikeapro/waha:latest
    envVars:
      - key: WHATSAPP_PORT
        value: "3000"
      - key: WHATSAPP_API_KEY
        sync: false
      - key: NODE_ENV
        value: "production"

databases: []
